language: generic
  sudo: required
  service:
    - docker

  before_install:
    - docker build -t naotookawa/docker-react -f Dockerfile.dev .

  script:
    - docker run -e CI=true naotookawa/docker-react npm run test